### ISSUE TITLE
Error:- object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Jitendra-Nathawat** [OlafenwaMoses/ImageAI#559] opened 2020-07-13 11:28 UTC
here is my code - 

from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory("/content/gdrive/My Drive/ImageAI/all")
trainer.setTrainConfig(object_names_array=["thumb_", "photo_", "emblum_", "barcode_", "bharat_"], batch_size=4, num_experiments=4, train_from_pretrained_model="/content/gdrive/My Drive/ImageAI/pretrained-yolov3.h5")
trainer.trainModel()

and here is my error ,, 

Using TensorFlow backend.

Generating anchor boxes for training images and annotation...
Average IOU for 9 anchors: 0.83
Anchor Boxes generated.
Detection configuration saved in  /content/gdrive/My Drive/ImageAI/all/json/detection_config.json
Some labels have no annotations! Please revise the list of labels in your configuration.
Training on: 	None
Training with Batch Size:  4
Number of Experiments:  4

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-8-c128d45c3f8b> in <module>()
      7 # In the above,when training for detecting multiple objects,
      8 #set object_names_array=["object1", "object2", "object3",..."objectz"]
----> 9 trainer.trainModel()

1 frames

/usr/local/lib/python3.6/dist-packages/imageai/Detection/Custom/generator.py in __init__(self, instances, anchors, labels, downsample, max_box_per_image, batch_size, min_net_size, max_net_size, shuffle, jitter, norm)
     34         self.net_w              = 416
     35 
---> 36         if shuffle: np.random.shuffle(self.instances)
     37 
     38     def __len__(self):

mtrand.pyx in numpy.random.mtrand.RandomState.shuffle()

TypeError: object of type 'NoneType' has no len()

ill train model many time but ill try first time this , i don't know why this error is coming , please help me to find it out.

**Comment by Combinacijus** [comment] 2020-07-16 13:34
Duplicate of #325 
This line might be the problem 

> Some labels have no annotations! Please revise the list of labels in your configuration.

**Closed** 2021-01-07 12:22 UTC

**Comment by NishaAkole** [comment] 2021-01-28 07:45
I tried suggestions from #325. Still, I am getting the same error.

**Comment by peoplecure** [comment] 2021-02-28 08:55
> I tried suggestions from #325. Still, I am getting the same error.

Can you show your code? Also, what is the name of your label(s) and file names?
